version: '3'
services:
  qdrant: # vector database 
    image: qdrant/qdrant
    container_name: llm_qdrant
    restart: always
    volumes:
     - ./data/llm/qdrant_storage:/qdrant/storage:z
  
  langfuse:
    image: ghcr.io/langfuse/langfuse:2
    container_name: llm_langfuse
    restart: always
    environment:
      - DATABASE_HOST=langfuse_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=Python123
      - DATABASE_NAME=postgres
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - SALT=${SALT}
      - HOST=0.0.0.0
    expose:
      - 3000

  langfuse_db:
    container_name: langfuse_pg13
    image: timescale/timescaledb:latest-pg13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Python123}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - ./data/llm/langfuse_db/db-data:/var/lib/postgresql/data/ # persist data even if container shuts down
